### ISSUE TITLE
Support optional chaining and nullish coalescing operators

### ISSUE THREAD

**Issue by steve-taylor** [solidjs/solid-scripts#22]
I'm using TypeScript, which supports the `?.` (optional chaining) and `??` (nullish coalescing) operators.

Unfortunately, I can't use these with solid-scripts, because Babel isn't configured to deal with them. The result is that TypeScript checking passes, but the Babel build fails. The workaround is to avoid these operators.

This can be fixed with the following plugins:

* [@babel/plugin-proposal-optional-chaining](https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining)
* [@babel/plugin-proposal-nullish-coalescing-operator](https://babeljs.io/docs/en/babel-plugin-proposal-nullish-coalescing-operator)

**Comment by ryansolid** [comment]
Hmm... I believe preset env should cover this especially given these are part of ES 2020. I seem to be having no issue with this in dev, build, and test. I can see the transformation in the final output. I installed the latest TS starter. I'm not sure what else it could be.

Node Version? Is your scripts project new? Is it up to date?

**Comment by steve-taylor** [comment]
Weird. I created this a day or two ago. It's using `solid-scripts@0.0.52` which uses `@babel/preset-env@^7.11.0`. Optional chaining and nullish coalescing were introduced in `@babel/preset-env@^7.8.0`, so I'm not sure why I'm getting this error:

```
Failed to compile.

./src/SudokuGrid.tsx 71:23
Module parse failed: Unexpected token (71:23)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   const _oldKnown = oldKnown ? oldKnown[x][y] : 0;
|
>   const _known = known?.[x][y] ?? 0;
|
|   const _oldSolved = oldSolved?.[x][y] ?? 0;
```

It was happening on the previous line, which I changed to use the tertiary operator instead.
